/** Stable Gateway startup/configuration error identifiers. */
export const CMCLOUD_AUTHORITY_REQUIRED = "CMCLOUD_AUTHORITY_REQUIRED" as const;
export const CMCLOUD_LEGACY_APRS_DISABLED =
  "CMCLOUD_LEGACY_APRS_DISABLED" as const;

export type GatewayBootstrapErrorCode =
  | typeof CMCLOUD_AUTHORITY_REQUIRED
  | "CALLMESH_CREDENTIAL_REJECTED"
  | "CALLMESH_UNAVAILABLE"
  | "GATEWAY_BOOTSTRAP_DEADLINE_INVALID"
  | "GATEWAY_BOOTSTRAP_EARLY_EOF"
  | "GATEWAY_BOOTSTRAP_FRAME_INVALID"
  | "GATEWAY_BOOTSTRAP_PIPE_FAILED"
  | "GATEWAY_BOOTSTRAP_TIMEOUT"
  | "GATEWAY_EXTERNAL_START_FAILED"
  | "GATEWAY_OWNERSHIP_ENDPOINT_INVALID"
  | "GATEWAY_PRIVATE_FRAME_INVALID"
  | "GATEWAY_PRIVATE_FRAME_OVERSIZED"
  | "GATEWAY_PRIVATE_FRAME_TRAILING_DATA"
  | "GATEWAY_READY_FRAME_INVALID"
  | "GATEWAY_READY_PIPE_FAILED"
  | "GATEWAY_SUPERVISION_REQUIRED"
  | "CMCLOUD_START_CONFIGURATION_INVALID"
  | "SETUP_MESHTASTIC_UNREACHABLE";

export type GatewayRuntimeConfigurationErrorCode =
  | typeof CMCLOUD_AUTHORITY_REQUIRED
  | typeof CMCLOUD_LEGACY_APRS_DISABLED
  | "APRS_ENABLED_CONFIGURATION_INVALID"
  | "APRS_ENCODING_CONFIGURATION_INVALID"
  | "APRS_ENDPOINT_CONFIGURATION_INVALID"
  | "APRS_OUTBOX_RETENTION_CONFIGURATION_INVALID"
  | "APRS_STATIC_IDENTITY_FORBIDDEN"
  | "CMCLOUD_CREDENTIAL_BOOTSTRAP_REQUIRED"
  | "CMCLOUD_DIRECT_APRS_ENABLED_CONFIGURATION_INVALID"
  | "CMCLOUD_DIRECT_APRS_FORBIDDEN"
  | "CMCLOUD_OUTBOX_RETENTION_CONFIGURATION_INVALID"
  | "CMCLOUD_PROXY_FORBIDDEN"
  | "GATEWAY_ID_CONFIGURATION_INVALID"
  | "JOB_RETENTION_CONFIGURATION_INVALID"
  | "MESHTASTIC_SERIAL_CONFIGURATION_INVALID"
  | "MESHTASTIC_SETUP_VALIDATION_TIMEOUT"
  | "MESHTASTIC_TCP_CONFIGURATION_INVALID"
  | "MESHTASTIC_TRANSPORT_CONFIGURATION_INVALID"
  | "MESH_NETWORK_CONFIGURATION_INVALID"
  | "MESSAGE_RETENTION_CONFIGURATION_INVALID"
  | "OBSERVATION_RETENTION_CONFIGURATION_INVALID"
  | "PHYSICAL_PROFILE_CONFIGURATION_INVALID"
  | "POSITION_RETENTION_CONFIGURATION_INVALID"
  | "TELEMETRY_RETENTION_CONFIGURATION_INVALID";
