#!/usr/bin/env python3

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

from v2_graph_test_fixture import write_v2_contract


SOURCE_ROOT = Path(__file__).resolve().parents[1]
TASK = "P13-T02"
SUBJECT = f"build(workflow): [{TASK}] exercise shell checkpoint"


def find_git_bash() -> Path:
    candidates = [
        Path(os.environ.get("ProgramFiles", r"C:\Program Files")) / "Git/bin/bash.exe",
        Path(os.environ.get("ProgramFiles", r"C:\Program Files")) / "Git/usr/bin/bash.exe",
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    fallback = shutil.which("bash")
    if fallback:
        return Path(fallback)
    raise unittest.SkipTest("Git Bash is required for workflow shell E2E tests")


BASH = find_git_bash()


def shell_path(path: Path) -> str:
    return path.resolve().as_posix()


def write_executable(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    path.chmod(0o755)


class ShellWorkspace:
    copied_scripts = (
        "checkpoint.sh",
        "start-session.sh",
        "reconcile-task-state.py",
        "task-state.py",
        "task-state-lib.py",
        "next-task.sh",
        "next-task.py",
    )

    def __init__(self, root: Path, *, create_repo: bool = True):
        self.root = root
        self.workspace = root / "workspace with spaces"
        self.scripts = self.workspace / "scripts"
        self.state = self.workspace / "state"
        self.repo = self.workspace / "repository/CMClient"
        self.remote = root / "remote bare repo.git"
        self.scripts.mkdir(parents=True)
        (self.scripts / "lib").mkdir()
        self.state.mkdir()
        for name in self.copied_scripts:
            shutil.copy2(SOURCE_ROOT / "scripts" / name, self.scripts / name)
            (self.scripts / name).chmod(0o755)
        shutil.copy2(
            SOURCE_ROOT / "scripts/lib/common.sh", self.scripts / "lib/common.sh"
        )
        write_executable(self.scripts / "doctor.sh", "#!/usr/bin/env bash\nexit 0\n")
        write_executable(
            self.scripts / "secret-scan.sh", "#!/usr/bin/env bash\nexit 0\n"
        )
        write_executable(
            self.scripts / "verify.sh",
            """#!/usr/bin/env bash
set -euo pipefail
source "$(cd "$(dirname "$0")" && pwd)/lib/common.sh"
if [[ -n "${CMCLIENT_TEST_VERIFY_CREATE:-}" ]]; then
  mkdir -p -- "$(dirname "$REPO_DIR/$CMCLIENT_TEST_VERIFY_CREATE")"
  printf 'generated by verify\n' > "$REPO_DIR/$CMCLIENT_TEST_VERIFY_CREATE"
fi
if [[ -n "${CMCLIENT_TEST_VERIFY_APPEND:-}" ]]; then
  printf 'verified\n' >> "$REPO_DIR/$CMCLIENT_TEST_VERIFY_APPEND"
fi
if [[ -n "${CMCLIENT_TEST_VERIFY_TOUCH_GRAPH_LOCK:-}" ]]; then
  printf '\n' >> "$WORKSPACE_ROOT/scripts/unified-task-graph-lock.json"
fi
exit "${CMCLIENT_TEST_VERIFY_STATUS:-0}"
""",
        )
        if create_repo:
            self.create_repository()

    @staticmethod
    def git(*arguments: str, cwd: Path) -> str:
        environment = {
            **os.environ,
            "GIT_AUTHOR_NAME": "CMClient Test",
            "GIT_AUTHOR_EMAIL": "cmclient-test@example.invalid",
            "GIT_COMMITTER_NAME": "CMClient Test",
            "GIT_COMMITTER_EMAIL": "cmclient-test@example.invalid",
            "GIT_TERMINAL_PROMPT": "0",
        }
        result = subprocess.run(
            ["git", *arguments],
            cwd=cwd,
            env=environment,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            encoding="utf-8",
        )
        if result.returncode != 0:
            raise AssertionError(
                f"git {' '.join(arguments)} failed:\n{result.stdout}\n{result.stderr}"
            )
        return result.stdout.strip()

    def create_repository(self) -> None:
        self.git("init", "--bare", str(self.remote), cwd=self.root)
        self.repo.parent.mkdir(parents=True)
        self.git("init", str(self.repo), cwd=self.root)
        self.git("checkout", "-b", "dev", cwd=self.repo)
        (self.repo / "feature.txt").write_text("base\n", encoding="utf-8")
        self.git("add", "feature.txt", cwd=self.repo)
        self.git("commit", "-m", "test(repo): establish shell baseline", cwd=self.repo)
        self.git("remote", "add", "origin", str(self.remote), cwd=self.repo)
        self.git("push", "-u", "origin", "dev", cwd=self.repo)
        self.base = self.git("rev-parse", "HEAD", cwd=self.repo)
        self.git(
            "symbolic-ref", "HEAD", "refs/heads/dev", cwd=self.remote
        )
        self.write_state()
        self.write_workspace_ledgers()

    def write_state(self, *, checkpoint_base: str | None = None, status: str = "in_progress") -> None:
        base = checkpoint_base if checkpoint_base is not None else self.base
        payload = {
            "schemaVersion": 2,
            "project": "CMClient shell test",
            "candidateInvalidations": [],
            "tasks": [
                {
                    "id": "P13-T01",
                    "phase": "P13",
                    "title": "dependency",
                    "status": "done",
                    "required": True,
                    "dependsOn": [],
                    "commit": self.base,
                    "startedAt": "2026-07-20T00:00:00+00:00",
                    "completedAt": "2026-07-20T00:01:00+00:00",
                    "notes": [],
                },
                {
                    "id": TASK,
                    "phase": "P13",
                    "title": "shell orchestration",
                    "status": status,
                    "required": True,
                    "dependsOn": ["P13-T01"],
                    "checkpointBaseCommit": base,
                    "commit": None,
                    "startedAt": "2026-07-20T00:02:00+00:00",
                    "completedAt": None,
                    "notes": [],
                },
            ],
        }
        write_v2_contract(
            payload,
            state_path=self.state / "TASKS.json",
            graph_lock_path=self.scripts / "unified-task-graph-lock.json",
            license_path=self.state / "LICENSE_PROVENANCE.json",
            source_baseline=base,
            origin=str(self.remote),
        )

    def write_workspace_ledgers(self) -> None:
        (self.state / "COMMITS.md").write_text(
            "# Checkpoint Commit Log\n\n"
            "| Time | Task | Commit | Subject | Verification |\n"
            "|---|---|---|---|---|\n",
            encoding="utf-8",
        )
        (self.state / "HANDOVER.md").write_text("# Handover\n", encoding="utf-8")

    def reset(self) -> None:
        hook = self.remote / "hooks/pre-receive"
        hook.unlink(missing_ok=True)
        self.git("update-ref", "refs/heads/dev", self.base, cwd=self.remote)
        self.git("checkout", "-B", "dev", self.base, cwd=self.repo)
        self.git("clean", "-fdx", cwd=self.repo)
        self.git("update-ref", "refs/remotes/origin/dev", self.base, cwd=self.repo)
        self.write_state()
        self.write_workspace_ledgers()

    def environment(self, *, auto_push: bool = True, **extra: str) -> dict[str, str]:
        environment = dict(os.environ)
        for name in tuple(environment):
            if name.startswith("CMCLIENT_"):
                environment.pop(name)
        environment.update(
            {
                "CMCLIENT_REPO_DIR": "repository/CMClient",
                "CMCLIENT_WORKSPACE_ROOT": self.workspace.resolve().as_posix(),
                "CMCLIENT_BRANCH": "dev",
                "CMCLIENT_REMOTE": "origin",
                "CMCLIENT_AUTO_PUSH": "1" if auto_push else "0",
                "CMCLIENT_PYTHON3": Path(sys.executable).resolve().as_posix(),
                "CMCLIENT_WINDOWS_CAMPAIGN_TOOLCHAIN": "0",
                "CMCLIENT_VERIFY_REPO_DIR": "",
                "GIT_AUTHOR_NAME": "CMClient Test",
                "GIT_AUTHOR_EMAIL": "cmclient-test@example.invalid",
                "GIT_COMMITTER_NAME": "CMClient Test",
                "GIT_COMMITTER_EMAIL": "cmclient-test@example.invalid",
                "GIT_TERMINAL_PROMPT": "0",
                **extra,
            }
        )
        return environment

    def run_script(
        self,
        name: str,
        *arguments: str,
        auto_push: bool = True,
        **extra_environment: str,
    ) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [str(BASH), shell_path(self.scripts / name), *arguments],
            cwd=self.workspace,
            env=self.environment(auto_push=auto_push, **extra_environment),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            encoding="utf-8",
        )

    def checkpoint(
        self, *, auto_push: bool = True, **extra_environment: str
    ) -> subprocess.CompletedProcess[str]:
        return self.run_script(
            "checkpoint.sh",
            "--task",
            TASK,
            "--type",
            "build",
            "--scope",
            "workflow",
            "--summary",
            "exercise shell checkpoint",
            auto_push=auto_push,
            **extra_environment,
        )

    def target(self) -> dict:
        payload = json.loads((self.state / "TASKS.json").read_text(encoding="utf-8"))
        return next(task for task in payload["tasks"] if task["id"] == TASK)

    def task_commit_count(self) -> int:
        subjects = self.git("log", "--all", "--format=%s", cwd=self.repo).splitlines()
        pattern = re.compile(rf"^[a-z]+\([a-z0-9-]+\): \[{TASK}\] ")
        return sum(pattern.match(subject) is not None for subject in subjects)

    def manual_checkpoint(self, *, push: bool) -> str:
        (self.repo / "feature.txt").write_text("manual checkpoint\n", encoding="utf-8")
        self.git("add", "feature.txt", cwd=self.repo)
        self.git(
            "commit",
            "-m",
            SUBJECT,
            "-m",
            f"Task: {TASK}\nValidation: passed\nChange: manual fixture",
            cwd=self.repo,
        )
        sha = self.git("rev-parse", "HEAD", cwd=self.repo)
        if push:
            self.git("push", "origin", "dev", cwd=self.repo)
        return sha


class CheckpointShellE2ETests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.temporary = tempfile.TemporaryDirectory(prefix="cmclient shell e2e ")
        cls.fixture = ShellWorkspace(Path(cls.temporary.name))

    @classmethod
    def tearDownClass(cls) -> None:
        cls.temporary.cleanup()

    def setUp(self) -> None:
        self.fx = self.fixture
        self.fx.reset()

    def test_no_auto_push_returns_20_then_retries_the_same_sha(self) -> None:
        (self.fx.repo / "feature.txt").rename(self.fx.repo / "renamed feature.txt")
        first = self.fx.checkpoint(
            auto_push=False, CMCLIENT_TEST_VERIFY_APPEND="renamed feature.txt"
        )
        self.assertEqual(first.returncode, 20, first.stderr)
        sha = self.fx.git("rev-parse", "HEAD", cwd=self.fx.repo)
        self.assertEqual(self.fx.target()["status"], "in_progress")
        self.assertEqual(
            self.fx.git("rev-parse", "refs/heads/dev", cwd=self.fx.remote), self.fx.base
        )
        self.assertEqual(self.fx.task_commit_count(), 1)
        self.assertIn(
            "verified",
            self.fx.git("show", f"{sha}:renamed feature.txt", cwd=self.fx.repo),
        )
        changed = self.fx.git(
            "diff-tree", "--no-commit-id", "--no-renames", "--name-status", "-r", sha,
            cwd=self.fx.repo,
        )
        self.assertIn("D\tfeature.txt", changed)
        self.assertIn("A\trenamed feature.txt", changed)

        retry = self.fx.checkpoint()
        self.assertEqual(retry.returncode, 0, retry.stderr)
        self.assertEqual(self.fx.git("rev-parse", "origin/dev", cwd=self.fx.repo), sha)
        self.assertEqual(self.fx.target()["status"], "done")
        self.assertEqual(self.fx.target()["commit"], sha)
        self.assertEqual(self.fx.task_commit_count(), 1)

    def test_pushed_before_state_is_reconciled_without_duplicate_commit(self) -> None:
        sha = self.fx.manual_checkpoint(push=True)
        recovered = self.fx.checkpoint()
        self.assertEqual(recovered.returncode, 0, recovered.stderr)
        self.assertEqual(self.fx.target()["status"], "done")
        self.assertEqual(self.fx.target()["commit"], sha)
        self.assertEqual(self.fx.task_commit_count(), 1)

    def test_push_failure_blocks_then_retries_the_same_commit(self) -> None:
        write_executable(
            self.fx.remote / "hooks/pre-receive",
            "#!/bin/sh\necho intentional push rejection >&2\nexit 1\n",
        )
        (self.fx.repo / "feature.txt").write_text("push failure change\n", encoding="utf-8")
        failed = self.fx.checkpoint()
        self.assertNotEqual(failed.returncode, 0)
        sha = self.fx.git("rev-parse", "HEAD", cwd=self.fx.repo)
        self.assertEqual(self.fx.target()["status"], "blocked")
        self.assertEqual(self.fx.target()["commit"], sha)
        self.assertEqual(self.fx.task_commit_count(), 1)
        self.assertEqual(
            self.fx.git("rev-parse", "refs/heads/dev", cwd=self.fx.remote), self.fx.base
        )

        (self.fx.remote / "hooks/pre-receive").unlink()
        retry = self.fx.checkpoint()
        self.assertEqual(retry.returncode, 0, retry.stderr)
        recovered = self.fx.target()
        self.assertEqual(recovered["status"], "done")
        self.assertEqual(recovered["commit"], sha)
        self.assertNotIn("blockedAt", recovered)
        self.assertNotIn("blockedByRepair", recovered)
        self.assertNotIn("blockReason", recovered)
        self.assertEqual(self.fx.task_commit_count(), 1)

    def test_checkpoint_base_and_verification_path_growth_fail_closed(self) -> None:
        self.fx.write_state(checkpoint_base="0" * 40)
        (self.fx.repo / "feature.txt").write_text("wrong base\n", encoding="utf-8")
        wrong_base = self.fx.checkpoint()
        self.assertNotEqual(wrong_base.returncode, 0)
        self.assertIn("checkpointBaseCommit", wrong_base.stderr)
        self.assertEqual(self.fx.git("rev-parse", "HEAD", cwd=self.fx.repo), self.fx.base)

        self.fx.reset()
        (self.fx.repo / "feature.txt").write_text("intended\n", encoding="utf-8")
        expanded = self.fx.checkpoint(
            CMCLIENT_TEST_VERIFY_CREATE="generated output.txt"
        )
        self.assertNotEqual(expanded.returncode, 0)
        self.assertIn("introduced changed paths", expanded.stderr)
        self.assertIn("generated output.txt", expanded.stderr)
        self.assertEqual(self.fx.git("rev-parse", "HEAD", cwd=self.fx.repo), self.fx.base)
        self.assertEqual(self.fx.target()["status"], "in_progress")

        self.fx.reset()
        (self.fx.repo / "feature.txt").write_text(
            "graph drift\n", encoding="utf-8"
        )
        drifted = self.fx.checkpoint(CMCLIENT_TEST_VERIFY_TOUCH_GRAPH_LOCK="1")
        self.assertNotEqual(drifted.returncode, 0)
        self.assertIn(
            "Task state, graph lock, or license provenance changed", drifted.stderr
        )
        self.assertEqual(
            self.fx.git("rev-parse", "HEAD", cwd=self.fx.repo), self.fx.base
        )

    def test_dirty_repository_never_recovers_or_duplicates_checkpoint(self) -> None:
        sha = self.fx.manual_checkpoint(push=False)
        (self.fx.repo / "unrelated dirty.txt").write_text("dirty\n", encoding="utf-8")
        result = self.fx.checkpoint()
        self.assertNotEqual(result.returncode, 0)
        self.assertEqual(self.fx.git("rev-parse", "HEAD", cwd=self.fx.repo), sha)
        self.assertEqual(self.fx.target()["status"], "in_progress")
        self.assertEqual(self.fx.task_commit_count(), 1)
        self.assertEqual(
            self.fx.git("rev-parse", "refs/heads/dev", cwd=self.fx.remote), self.fx.base
        )


class StartSessionLinkedWorktreeE2ETest(unittest.TestCase):
    def test_half_complete_graph_upgrade_journal_stops_before_doctor(self) -> None:
        with tempfile.TemporaryDirectory(prefix="cmclient corrupt shell ") as temporary:
            fx = ShellWorkspace(Path(temporary))
            (fx.state / "GRAPH_UPGRADE.json").write_text(
                json.dumps(
                    {
                        "schema": "cmclient-graph-upgrade-journal/v1",
                        "operationId": "upgrade-shell-fixture",
                        "status": "complete",
                        "phase": "pushed",
                    },
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            result = fx.run_script("start-session.sh")
            self.assertNotEqual(result.returncode, 0)
            self.assertIn("half complete", result.stderr)
            self.assertNotIn("Next executable task", result.stdout)

    def test_incomplete_graph_upgrade_is_resumed_before_normal_recovery(self) -> None:
        with tempfile.TemporaryDirectory(prefix="cmclient upgrade shell ") as temporary:
            fx = ShellWorkspace(Path(temporary))
            journal = fx.state / "GRAPH_UPGRADE.json"
            journal.write_text(
                json.dumps(
                    {
                        "schema": "cmclient-graph-upgrade-journal/v1",
                        "operationId": "upgrade-shell-fixture",
                        "status": "running",
                        "phase": "checkpointed",
                    },
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            (fx.scripts / "upgrade-unified-task-graph-v2.py").write_text(
                """from pathlib import Path
import json

root = Path(__file__).resolve().parents[1]
journal_path = root / "state/GRAPH_UPGRADE.json"
journal = json.loads(journal_path.read_text(encoding="utf-8"))
journal["status"] = "complete"
journal["phase"] = "complete"
journal_path.write_text(json.dumps(journal, indent=2) + "\\n", encoding="utf-8")
(root / "state/UPGRADE_RESUMED").write_text("yes\\n", encoding="utf-8")
""",
                encoding="utf-8",
            )

            result = fx.run_script("start-session.sh")
            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertEqual(
                (fx.state / "UPGRADE_RESUMED").read_text(encoding="utf-8"),
                "yes\n",
            )
            completed = json.loads(journal.read_text(encoding="utf-8"))
            self.assertEqual(completed["phase"], "complete")

    def test_linked_worktree_git_file_is_detected_and_synced(self) -> None:
        with tempfile.TemporaryDirectory(prefix="cmclient linked shell ") as temporary:
            root = Path(temporary)
            fx = ShellWorkspace(root, create_repo=False)
            fx.git("init", "--bare", str(fx.remote), cwd=root)
            primary = root / "primary checkout"
            fx.git("init", str(primary), cwd=root)
            fx.git("checkout", "-b", "dev", cwd=primary)
            (primary / "feature.txt").write_text("base\n", encoding="utf-8")
            fx.git("add", "feature.txt", cwd=primary)
            fx.git("commit", "-m", "test(repo): linked baseline", cwd=primary)
            fx.git("remote", "add", "origin", str(fx.remote), cwd=primary)
            fx.git("push", "-u", "origin", "dev", cwd=primary)
            fx.base = fx.git("rev-parse", "HEAD", cwd=primary)
            fx.git("symbolic-ref", "HEAD", "refs/heads/dev", cwd=fx.remote)
            fx.git("checkout", "-b", "holder", cwd=primary)
            fx.repo.parent.mkdir(parents=True)
            fx.git("worktree", "add", str(fx.repo), "dev", cwd=primary)
            self.assertTrue((fx.repo / ".git").is_file())
            fx.write_state(status="pending")
            fx.write_workspace_ledgers()

            result = fx.run_script("start-session.sh")
            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertIn("Fast-forward sync complete for dev", result.stdout)
            self.assertIn(TASK, result.stdout)


if __name__ == "__main__":
    unittest.main(verbosity=2)
